apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: hellovm-v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hellovm.info
    http:
      paths:
      - path: /
        backend:
          serviceName: hellovm-v1
          servicePort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellovm-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
      service: hellodocker
      version: 0.0.1
  template:
    metadata:
      labels:
        type: app
        service: hellodocker
        version: 0.0.1
    spec:
      containers:
      - name: hellodocker
        image: ec209/hellodocker:0.0.1
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: hellovm-v1
spec:
  selector:
    app: hellodocker
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000

