apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hellovm-v1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
    nginx.org/server-snippet: "proxy_ssl_verify off;"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hellovm-v1
          servicePort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellovm-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
      service: hellodocker
      version: 0.0.1
  template:
    metadata:
      labels:
        type: app
        service: hellodocker
        version: 0.0.1
    spec:
      containers:
      - name: hellodocker
        image: ec209/hellodocker
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: hellovm-v1
spec:
  selector:
    type: app
    service: hellodocker
    version: 0.0.1
  
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http

