apiVersion: v1
kind: Pod
metadata:
  name: hellovm-lp
  labels:
    type: app
spec:
  containers:
  - name: app
    image: ec209/python:ver3
    livenessProbe:
      httpGet:
        path: /not/exist
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2 # Default 1
      periodSeconds: 5 # Defaults 10
      failureThreshold: 1 # Defaults 3
