apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hellovm-v1
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/server-snippet: "proxy_ssl_verify off;"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hellovm-v1-svc
          servicePort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellovm-v1-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellovm-v1-app
  template:
    metadata:
      labels:
        app: hellovm-v1-app
    spec:
      containers:
      - name: hellodocker
        image: ec209/hellodocker:0.0.1
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: hellovm-v1-svc
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30032
  selector:
    app: hellovm-v1-app
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
      


