apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hellovm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hellovm.info
    http:
      paths: 
      - path: /
        backend:
          serviceName: hellovm
          servicePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellovm
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
      service: hellodocker
      version: 0.0.1
  template:
    metadata:
      labels:
        type: app
        service: hellodocker
        version: 0.0.1
    spec:
      containers:
      - name: hellodocker
        image: ec209/hellodocker:0.0.1
        livenessProbe:
          httpGet:
            path: /
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hellovm
spec:
  type:NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    type: app
    service: hellodocker
    version: 0.0.1
